services:
  backend-server:
    image: kaetaro13/beats-game-server
    container_name: backend-server
    ports:
      - "127.0.0.1:8081:8085"
    env_file:
      - ./.env
    networks:
      - gmr-beats-server-bun-ts_ann-network  # Use the existing network
    restart: always
    
  game-server:
    image: kaetaro13/godot-server:latest
    container_name: game-server
    ports:
      - "127.0.0.1:8090:8087/tcp"
      - "127.0.0.1:8090:8087/udp"
    environment:
      KEYDB_PASSWORD: "${KEYDB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    networks:
      - gmr-beats-server-bun-ts_ann-network  
    restart: always
    pull_policy: always


networks:
  gmr-beats-server-bun-ts_ann-network:
    external: true  # Make the network external so Docker Compose doesn't try to create a new one
